Public Class TipoToken
    Friend Function retornarToken(v As String) As Object
        Select Case v
            Case "INSTRUCCIONES"
                Return "Palabra Reservada"
            Case "VARIABLES"
                Return "Palabra Reservada"
            Case "TEXTO"
                Return "Palabra Reservada"
            Case "INTERLINEADO"
                Return "Palabra Reservada"
            Case "TAMANIO_LETRA"
                Return "Palabra Reservada"
            Case "NOMBRE_ARCHIVO"
                Return "Palabra Reservada"
            Case "DIRECCION_ARCHIVO"
                Return "Palabra Reservada"
            Case "IMAGEN"
                Return "Palabra Reservada"
            Case "NUMEROS"
                Return "Palabra Reservada"
            Case "VAR"
                Return "Palabra Reservada"
            Case "PROMEDIO"
                Return "Palabra Reservada"
            Case "SUMA"
                Return "Palabra Reservada"
            Case "ASIGNAR"
                Return "Palabra Reservada"
            Case "ENTERO"
                Return "Palabra Reservada"
            Case "CADENA"
                Return "Palabra Reservada"
            Case "ID"
                Return "Identificador"
            Case "TEXTO"
                Return "Cadena"
            Case "NUMERO"
                Return "Número"
            Case "RNUMERO"
                Return "Número Real"
            Case "{"
                Return "Llave de Inicio"
            Case "}"
                Return "Llave de Cierre"
            Case "("
                Return "Paréntesis de Inicio"
            Case ")"
                Return "Paréntesis de Cierre"
            Case ":"
                Return "Dos Puntos"
            Case Chr(34)
                Return "Comilla"
            Case "/"
                Return "Barra"
            Case "*"
                Return "Asterisco"
            Case ";"
                Return "Punto y Coma"
            Case "["
                Return "Corchete de Inicio"
            Case "]"
                Return "Corchete de Cierre"
            Case Else
                Return "Caracter no identificado"
        End Select
    End Function
End Class
